# Generated by Django 4.2 on 2023-05-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
            ],
        ),
    ]
