# Generated by Django 4.2 on 2023-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(default='Noturno', max_length=5, verbose_name='Turno'),
        ),
    ]
