# Generated by Django 4.2 on 2023-04-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sigla',
            field=models.CharField(max_length=5, verbose_name='Sigra'),
        ),
    ]
