# Generated by Django 4.2 on 2023-06-26 17:17

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, error_messages={'unique': 'Este CPF já está cadastrada no sistema.'}, help_text='CPF do sem pontos e traços', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
